USE [master]
GO

/****** Object:  Database [PROYECTO_APP_POS]    Script Date: 07/09/2021 23:40:29 ******/
CREATE DATABASE [PROYECTO_APP_POS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PROYECTO_APP_POS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\PROYECTO_APP_POS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PROYECTO_APP_POS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\PROYECTO_APP_POS_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PROYECTO_APP_POS] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PROYECTO_APP_POS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PROYECTO_APP_POS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET ARITHABORT OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET  MULTI_USER 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PROYECTO_APP_POS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PROYECTO_APP_POS] SET  READ_WRITE 
GO

