USE [master]
GO

/****** Object:  Database [ProyectoAppAtuServicio]    Script Date: 07/09/2021 22:55:29 ******/
CREATE DATABASE [ProyectoAppAtuServicio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProyectoAppAtuServicio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProyectoAppAtuServicio.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProyectoAppAtuServicio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProyectoAppAtuServicio_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProyectoAppAtuServicio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET  MULTI_USER 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProyectoAppAtuServicio] SET  READ_WRITE 
GO

